import uuid
from decimal import Decimal

from django.core.management.base import BaseCommand

from mobiles.models import Mobile

SEED_NS = uuid.UUID("00000000-0000-0000-0000-00000000e001")


def mid(key: str) -> uuid.UUID:
    return uuid.uuid5(SEED_NS, f"mobile:{key}")


class Command(BaseCommand):
    help = "Seed mobiles with mock data"

    def handle(self, *args, **options):
        Mobile.objects.all().delete()

        mobiles_data = [
            {
                "id": mid("iphone-15"),
                "name": "iPhone 15",
                "brand": "Apple",
                "os": "iOS",
                "cpu_chip": "Apple A16 Bionic",
                "ram": 6,
                "storage": 128,
                "battery": 3349,
                "screen_size": 6.1,
                "camera_main": 48,
                "camera_front": 12,
                "price": Decimal("19990000"),
                "stock": 30,
                "image_url": "https://picsum.photos/seed/iphone-15/480/320",
                "description": "Dynamic Island, USB-C, camera 48MP.",
            },
            {
                "id": mid("iphone-15-pro-max"),
                "name": "iPhone 15 Pro Max",
                "brand": "Apple",
                "os": "iOS",
                "cpu_chip": "Apple A17 Pro",
                "ram": 8,
                "storage": 256,
                "battery": 4441,
                "screen_size": 6.7,
                "camera_main": 48,
                "camera_front": 12,
                "price": Decimal("33990000"),
                "stock": 18,
                "image_url": "https://picsum.photos/seed/iphone-15-pro-max/480/320",
                "description": "Titanium khung viền, zoom tiềm vọng 5x.",
            },
            {
                "id": mid("s24-ultra"),
                "name": "Samsung Galaxy S24 Ultra",
                "brand": "Samsung",
                "os": "Android",
                "cpu_chip": "Snapdragon 8 Gen 3 for Galaxy",
                "ram": 12,
                "storage": 256,
                "battery": 5000,
                "screen_size": 6.8,
                "camera_main": 200,
                "camera_front": 12,
                "price": Decimal("31990000"),
                "stock": 14,
                "image_url": "https://picsum.photos/seed/s24-ultra/480/320",
                "description": "S Pen tích hợp, Galaxy AI, màn Dynamic AMOLED 2X.",
            },
            {
                "id": mid("galaxy-a55"),
                "name": "Samsung Galaxy A55",
                "brand": "Samsung",
                "os": "Android",
                "cpu_chip": "Exynos 1480",
                "ram": 8,
                "storage": 128,
                "battery": 5000,
                "screen_size": 6.6,
                "camera_main": 50,
                "camera_front": 32,
                "price": Decimal("8990000"),
                "stock": 40,
                "image_url": "https://picsum.photos/seed/galaxy-a55/480/320",
                "description": "Tầm trung bền bỉ, hỗ trợ 5G.",
            },
            {
                "id": mid("xiaomi-14"),
                "name": "Xiaomi 14",
                "brand": "Xiaomi",
                "os": "Android",
                "cpu_chip": "Snapdragon 8 Gen 3",
                "ram": 12,
                "storage": 256,
                "battery": 4610,
                "screen_size": 6.36,
                "camera_main": 50,
                "camera_front": 32,
                "price": Decimal("22990000"),
                "stock": 22,
                "image_url": "https://picsum.photos/seed/xiaomi-14/480/320",
                "description": "Ống kính Leica, sạc nhanh 90W.",
            },
            {
                "id": mid("redmi-note-13-pro"),
                "name": "Xiaomi Redmi Note 13 Pro",
                "brand": "Xiaomi",
                "os": "Android",
                "cpu_chip": "Snapdragon 7s Gen 2",
                "ram": 8,
                "storage": 256,
                "battery": 5100,
                "screen_size": 6.67,
                "camera_main": 200,
                "camera_front": 16,
                "price": Decimal("6990000"),
                "stock": 55,
                "image_url": "https://picsum.photos/seed/redmi-note-13-pro/480/320",
                "description": "Camera 200MP giá rẻ, màn AMOLED 120Hz.",
            },
            {
                "id": mid("oppo-reno-11"),
                "name": "Oppo Reno 11",
                "brand": "Oppo",
                "os": "Android",
                "cpu_chip": "MediaTek Dimensity 7050",
                "ram": 12,
                "storage": 256,
                "battery": 5000,
                "screen_size": 6.7,
                "camera_main": 50,
                "camera_front": 32,
                "price": Decimal("10990000"),
                "stock": 28,
                "image_url": "https://picsum.photos/seed/oppo-reno-11/480/320",
                "description": "Thiết kế Reno đặc trưng, portrait nổi bật.",
            },
            {
                "id": mid("oppo-a98"),
                "name": "Oppo A98",
                "brand": "Oppo",
                "os": "Android",
                "cpu_chip": "Snapdragon 695",
                "ram": 8,
                "storage": 256,
                "battery": 5000,
                "screen_size": 6.72,
                "camera_main": 64,
                "camera_front": 32,
                "price": Decimal("7990000"),
                "stock": 35,
                "image_url": "https://picsum.photos/seed/oppo-a98/480/320",
                "description": "Pin lớn, sạc siêu nhanh 67W.",
            },
            {
                "id": mid("vivo-v30"),
                "name": "Vivo V30",
                "brand": "Vivo",
                "os": "Android",
                "cpu_chip": "Snapdragon 7 Gen 3",
                "ram": 12,
                "storage": 256,
                "battery": 5000,
                "screen_size": 6.78,
                "camera_main": 50,
                "camera_front": 50,
                "price": Decimal("12490000"),
                "stock": 20,
                "image_url": "https://picsum.photos/seed/vivo-v30/480/320",
                "description": "Chụp chân dung Aura Light, màn cong AMOLED.",
            },
            {
                "id": mid("vivo-y36"),
                "name": "Vivo Y36",
                "brand": "Vivo",
                "os": "Android",
                "cpu_chip": "Snapdragon 680",
                "ram": 8,
                "storage": 128,
                "battery": 5000,
                "screen_size": 6.64,
                "camera_main": 50,
                "camera_front": 16,
                "price": Decimal("5490000"),
                "stock": 45,
                "image_url": "https://picsum.photos/seed/vivo-y36/480/320",
                "description": "Phân khúc phổ thông, pin bền.",
            },
            {
                "id": mid("realme-gt-5"),
                "name": "Realme GT 5",
                "brand": "Realme",
                "os": "Android",
                "cpu_chip": "Snapdragon 8 Gen 2",
                "ram": 12,
                "storage": 256,
                "battery": 5240,
                "screen_size": 6.74,
                "camera_main": 50,
                "camera_front": 16,
                "price": Decimal("14990000"),
                "stock": 17,
                "image_url": "https://picsum.photos/seed/realme-gt-5/480/320",
                "description": "Hiệu năng flagship, sạc 240W (tùy phiên bản).",
            },
            {
                "id": mid("oneplus-12"),
                "name": "OnePlus 12",
                "brand": "OnePlus",
                "os": "Android",
                "cpu_chip": "Snapdragon 8 Gen 3",
                "ram": 16,
                "storage": 512,
                "battery": 5400,
                "screen_size": 6.82,
                "camera_main": 50,
                "camera_front": 32,
                "price": Decimal("26990000"),
                "stock": 12,
                "image_url": "https://picsum.photos/seed/oneplus-12/480/320",
                "description": "Hợp tác Hasselblad, màn 2K LTPO.",
            },
            {
                "id": mid("pixel-8"),
                "name": "Google Pixel 8",
                "brand": "Google",
                "os": "Android",
                "cpu_chip": "Google Tensor G3",
                "ram": 8,
                "storage": 128,
                "battery": 4575,
                "screen_size": 6.2,
                "camera_main": 50,
                "camera_front": 10,
                "price": Decimal("17990000"),
                "stock": 16,
                "image_url": "https://picsum.photos/seed/pixel-8/480/320",
                "description": "AI Google Photos, cập nhật phần mềm dài hạn.",
            },
            {
                "id": mid("nothing-phone-2"),
                "name": "Nothing Phone 2",
                "brand": "Nothing",
                "os": "Android",
                "cpu_chip": "Snapdragon 8+ Gen 1",
                "ram": 12,
                "storage": 256,
                "battery": 4700,
                "screen_size": 6.7,
                "camera_main": 50,
                "camera_front": 32,
                "price": Decimal("15990000"),
                "stock": 14,
                "image_url": "https://picsum.photos/seed/nothing-phone-2/480/320",
                "description": "Glyph Interface độc đáo, thiết kế trong suốt.",
            },
            {
                "id": mid("sony-xperia-5-v"),
                "name": "Sony Xperia 5 V",
                "brand": "Sony",
                "os": "Android",
                "cpu_chip": "Snapdragon 8 Gen 2",
                "ram": 8,
                "storage": 128,
                "battery": 5000,
                "screen_size": 6.1,
                "camera_main": 48,
                "camera_front": 12,
                "price": Decimal("24990000"),
                "stock": 9,
                "image_url": "https://picsum.photos/seed/sony-xperia-5-v/480/320",
                "description": "Tỷ lệ 21:9, phần mềm chụp ảnh chuyên nghiệp.",
            },
        ]

        for data in mobiles_data:
            pk = data["id"]
            defaults = {k: v for k, v in data.items() if k != "id"}
            obj, _ = Mobile.objects.update_or_create(id=pk, defaults=defaults)
            self.stdout.write(self.style.SUCCESS(f"✓ Created: {obj.name}"))
