server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 8000
        response-timeout: 60s
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false

management:
  endpoints:
    web:
      exposure:
        include: health,gateway
  endpoint:
    health:
      show-details: when_authorized
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
