import uuid
from decimal import Decimal

from django.core.management.base import BaseCommand

from laptops.models import Laptop

SEED_NS = uuid.UUID("00000000-0000-0000-0000-00000000e001")


def lid(key: str) -> uuid.UUID:
    return uuid.uuid5(SEED_NS, f"laptop:{key}")


class Command(BaseCommand):
    help = "Seed laptops with mock data"

    def handle(self, *args, **options):
        Laptop.objects.all().delete()

        laptops_data = [
            {
                "id": lid("dell-xps-13"),
                "name": "Dell XPS 13",
                "brand": "Dell",
                "cpu": "Intel Core i7-1360P",
                "ram": 16,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": "Intel Iris Xe",
                "screen_size": 13.4,
                "price": Decimal("28990000"),
                "stock": 12,
                "image_url": "https://picsum.photos/seed/dell-xps-13/480/320",
                "description": "Ultrabook mỏng nhẹ, màn hình InfinityEdge, pin cả ngày.",
            },
            {
                "id": lid("dell-inspiron-15"),
                "name": "Dell Inspiron 15",
                "brand": "Dell",
                "cpu": "Intel Core i5-1335U",
                "ram": 8,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": None,
                "screen_size": 15.6,
                "price": Decimal("15990000"),
                "stock": 20,
                "image_url": "https://picsum.photos/seed/dell-inspiron-15/480/320",
                "description": "Laptop phổ thông đa năng cho học tập và văn phòng.",
            },
            {
                "id": lid("hp-pavilion-15"),
                "name": "HP Pavilion 15",
                "brand": "HP",
                "cpu": "AMD Ryzen 7 7730U",
                "ram": 16,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": "AMD Radeon Graphics",
                "screen_size": 15.6,
                "price": Decimal("19990000"),
                "stock": 15,
                "image_url": "https://picsum.photos/seed/hp-pavilion-15/480/320",
                "description": "Hiệu năng ổn định, âm thanh B&O tinh chỉnh.",
            },
            {
                "id": lid("hp-envy-x360"),
                "name": "HP Envy x360",
                "brand": "HP",
                "cpu": "AMD Ryzen 5 7530U",
                "ram": 8,
                "storage": 256,
                "storage_type": "SSD",
                "gpu": None,
                "screen_size": 14,
                "price": Decimal("18990000"),
                "stock": 10,
                "image_url": "https://picsum.photos/seed/hp-envy-x360/480/320",
                "description": "2-in-1 cảm ứng xoay gập 360°, màu bạc sang trọng.",
            },
            {
                "id": lid("asus-vivobook-15"),
                "name": "Asus VivoBook 15",
                "brand": "Asus",
                "cpu": "Intel Core i5-1235U",
                "ram": 8,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": None,
                "screen_size": 15.6,
                "price": Decimal("13990000"),
                "stock": 25,
                "image_url": "https://picsum.photos/seed/asus-vivobook-15/480/320",
                "description": "Nhập môn giá tốt, nắp màu trẻ trung.",
            },
            {
                "id": lid("asus-rog-strix-g15"),
                "name": "Asus ROG Strix G15",
                "brand": "Asus",
                "cpu": "AMD Ryzen 9 7945HX",
                "ram": 16,
                "storage": 1024,
                "storage_type": "SSD",
                "gpu": "NVIDIA GeForce RTX 4060",
                "screen_size": 15.6,
                "price": Decimal("42990000"),
                "stock": 6,
                "image_url": "https://picsum.photos/seed/asus-rog-strix-g15/480/320",
                "description": "Gaming hiệu năng cao, tản nhiệt tối ưu.",
            },
            {
                "id": lid("lenovo-thinkpad-x1"),
                "name": "Lenovo ThinkPad X1 Carbon",
                "brand": "Lenovo",
                "cpu": "Intel Core i7-1365U",
                "ram": 16,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": None,
                "screen_size": 14,
                "price": Decimal("51990000"),
                "stock": 7,
                "image_url": "https://picsum.photos/seed/thinkpad-x1/480/320",
                "description": "Doanh nhân, bàn phím ThinkPad huyền thoại.",
            },
            {
                "id": lid("lenovo-ideapad-5"),
                "name": "Lenovo IdeaPad 5",
                "brand": "Lenovo",
                "cpu": "AMD Ryzen 7 5825U",
                "ram": 16,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": None,
                "screen_size": 15.6,
                "price": Decimal("16990000"),
                "stock": 18,
                "image_url": "https://picsum.photos/seed/lenovo-ideapad-5/480/320",
                "description": "Cân bằng giá và cấu hình cho sinh viên.",
            },
            {
                "id": lid("apple-macbook-air-m2"),
                "name": "Apple MacBook Air M2",
                "brand": "Apple",
                "cpu": "Apple M2 8-core",
                "ram": 8,
                "storage": 256,
                "storage_type": "SSD",
                "gpu": "GPU 8-core tích hợp",
                "screen_size": 13.6,
                "price": Decimal("25990000"),
                "stock": 14,
                "image_url": "https://picsum.photos/seed/macbook-air-m2/480/320",
                "description": "Siêu mỏng nhẹ, chip M2 tiết kiệm điện.",
            },
            {
                "id": lid("apple-macbook-pro-14-m3"),
                "name": "Apple MacBook Pro 14 M3",
                "brand": "Apple",
                "cpu": "Apple M3 Pro 11-core",
                "ram": 18,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": "GPU 14-core tích hợp",
                "screen_size": 14.2,
                "price": Decimal("57990000"),
                "stock": 5,
                "image_url": "https://picsum.photos/seed/macbook-pro-14-m3/480/320",
                "description": "Màn hình Liquid Retina XDR, sáng tạo nội dung chuyên nghiệp.",
            },
            {
                "id": lid("acer-aspire-5"),
                "name": "Acer Aspire 5",
                "brand": "Acer",
                "cpu": "Intel Core i5-12450H",
                "ram": 8,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": None,
                "screen_size": 15.6,
                "price": Decimal("12990000"),
                "stock": 22,
                "image_url": "https://picsum.photos/seed/acer-aspire-5/480/320",
                "description": "Laptop văn phòng giá mềm, bàn phím có đèn nền.",
            },
            {
                "id": lid("acer-nitro-5"),
                "name": "Acer Nitro 5",
                "brand": "Acer",
                "cpu": "Intel Core i5-12500H",
                "ram": 16,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": "NVIDIA GeForce RTX 3050",
                "screen_size": 15.6,
                "price": Decimal("21990000"),
                "stock": 11,
                "image_url": "https://picsum.photos/seed/acer-nitro-5/480/320",
                "description": "Gaming tầm trung, tản nhiệt kép.",
            },
            {
                "id": lid("msi-modern-14"),
                "name": "MSI Modern 14",
                "brand": "MSI",
                "cpu": "Intel Core i7-1355U",
                "ram": 16,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": None,
                "screen_size": 14,
                "price": Decimal("17990000"),
                "stock": 13,
                "image_url": "https://picsum.photos/seed/msi-modern-14/480/320",
                "description": "Mỏng nhẹ cho creator, pin dài.",
            },
            {
                "id": lid("gigabyte-aero-16"),
                "name": "Gigabyte Aero 16",
                "brand": "Gigabyte",
                "cpu": "Intel Core i7-13700H",
                "ram": 32,
                "storage": 1024,
                "storage_type": "SSD",
                "gpu": "NVIDIA GeForce RTX 4060",
                "screen_size": 16,
                "price": Decimal("48990000"),
                "stock": 4,
                "image_url": "https://picsum.photos/seed/gigabyte-aero-16/480/320",
                "description": "Màn OLED 4K, chỉnh màu chuẩn cho đồ họa.",
            },
            {
                "id": lid("lg-gram-16"),
                "name": "LG Gram 16",
                "brand": "LG",
                "cpu": "Intel Core i7-1360P",
                "ram": 16,
                "storage": 512,
                "storage_type": "SSD",
                "gpu": None,
                "screen_size": 16,
                "price": Decimal("34990000"),
                "stock": 8,
                "image_url": "https://picsum.photos/seed/lg-gram-16/480/320",
                "description": "Siêu nhẹ ~1,2kg cho màn 16 inch, pin lớn.",
            },
        ]

        for data in laptops_data:
            pk = data["id"]
            defaults = {k: v for k, v in data.items() if k != "id"}
            obj, _ = Laptop.objects.update_or_create(id=pk, defaults=defaults)
            self.stdout.write(self.style.SUCCESS(f"✓ Created: {obj.name}"))
